#!/bin/bash
set -e

# This script is executed by postgres when the container starts
# It creates multiple databases and users as specified in the environment variables

echo "Creating databases and users..."

# Create metadata database and user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $METADATA_DATABASE_NAME;
    CREATE USER $METADATA_DATABASE_USERNAME WITH PASSWORD '$METADATA_DATABASE_PASSWORD';
    ALTER DATABASE $METADATA_DATABASE_NAME OWNER TO $METADATA_DATABASE_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE $METADATA_DATABASE_NAME TO $METADATA_DATABASE_USERNAME;
EOSQL

# Create celery results database and user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $CELERY_BACKEND_NAME;
    CREATE USER $CELERY_BACKEND_USERNAME WITH PASSWORD '$CELERY_BACKEND_PASSWORD';
    ALTER DATABASE $CELERY_BACKEND_NAME OWNER TO $CELERY_BACKEND_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE $CELERY_BACKEND_NAME TO $CELERY_BACKEND_USERNAME;
EOSQL

# Create ELT database and user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $ELT_DATABASE_NAME;
    CREATE USER $ELT_DATABASE_USERNAME WITH PASSWORD '$ELT_DATABASE_PASSWORD';
    ALTER DATABASE $ELT_DATABASE_NAME OWNER TO $ELT_DATABASE_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE $ELT_DATABASE_NAME TO $ELT_DATABASE_USERNAME;
EOSQL

echo "Databases and users created successfully!"
